name: "🚀 Build and Test"

on: # rebuild any PRs and main & release branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

# ---------------------------------------------------------------------------------------

  build: # make sure build/ci works properly (action development)

# ---------------------------------------------------------------------------------------

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2 # https://github.com/actions/checkout

      - run: |
          npm install

      - run: |
          npm run all

# ---------------------------------------------------------------------------------------

  test: # make sure the action works on a clean machine without building (user case)

# ---------------------------------------------------------------------------------------

    name: Build on ${{ matrix.config.OS }}
    runs-on: ${{ matrix.config.OS }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
          - { OS: windows-2022 }
          - { OS: ubuntu-22.04  }

    steps:

      - name: 🤘 Checkout Code
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Use own action
        uses: ./
        with:
          # Vulkan SDK version to download. Default: latest version.
          version: 1.3.216.0
          # test with intentionally wrong version
          # should say version not available
          # should print list of valid versions
          #version: 1.2.189.1

      - run: echo vulkan-version=${{ steps.install-vulkan-sdk-action.outputs.vulkan-version }}

      - run: echo $PATH

      - run: echo $VULKAN_VERSION

      - run: echo $VULKAN_SDK
